version: '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3343:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - db
    php:
        build: docker/php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./:/var/www:cached
            - ./logs/formastore:/var/www/var/log:cached
        depends_on: 
            - db
        networks:
            - db
            - php
    nginx:
        build: docker/nginx
        ports:
            - "80:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/www:cached
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8088:80
        networks:
            - db
            - php
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"
        networks:
            elk_stack:
                aliases:
                    - "elasticsearch"
    logstash:
        image: docker.elastic.co/logstash/logstash:7.9.3
        depends_on: 
            - elasticsearch
        volumes:
            - ./docker/elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./docker/elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ./logs/formastore:/var/www/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
        networks:
            - elk_stack
    kibana:
        depends_on: 
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.9.3
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - elk_stack
        ports:
            - "81:5601"
networks:
    db:
    php:
    elk_stack:
